import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LandProject, UserRole } from '../types';

export interface ReportFilterMetadata {
  state?: string;
  district?: string;
  projectType?: string;
  stage?: string;
  risk?: string;
  searchQuery?: string;
  userRole?: UserRole;
  officerName?: string;
  officerDesignation?: string;
  notes?: string;
}

/**
 * Generate a unique formal document reference number
 */
export function generateDocRef(prefix: string = 'DoLR-NLADSS'): string {
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const randomSuffix = Math.floor(1000 + Math.random() * 9000);
  return `${prefix}/REP/${dateStr}/${randomSuffix}`;
}

/**
 * Format currency in Indian Crores (₹ Cr)
 */
function formatCr(val: number | undefined | null): string {
  if (val === undefined || val === null) return '₹0.00 Cr';
  return `₹${val.toFixed(2)} Cr`;
}

// ==========================================
// 1. PROJECT LIST EXCEL EXPORT (.XLSX)
// ==========================================
export function exportProjectListToExcel(
  projects: LandProject[],
  metadata: ReportFilterMetadata = {},
  fileNamePrefix: string = 'DoLR_Project_Status_Register'
): void {
  const wb = XLSX.utils.book_new();
  const timestamp = new Date().toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
  const docRef = generateDocRef('DoLR-PLIST');

  // Sheet 1: Master Projects Register
  const titleRows = [
    ['GOVERNMENT OF INDIA - MINISTRY OF RURAL DEVELOPMENT'],
    ['DEPARTMENT OF LAND RESOURCES (DoLR) | NATIONAL LAND ACQUISITION DELAY SURVEILLANCE SYSTEM'],
    ['STATUTORY PROJECT STATUS & EARLY DELAY RISK REGISTER (RFCTLARR ACT, 2013)'],
    [],
    ['Document Reference:', docRef, '', 'Generated Date & Time:', timestamp],
    [
      'Generated By Role:',
      metadata.userRole || 'Authorized Land Acquisition Officer',
      '',
      'Total Records Included:',
      projects.length,
    ],
    [
      'Filters Applied:',
      `State: ${metadata.state || 'All'} | District: ${metadata.district || 'All'} | Type: ${
        metadata.projectType || 'All'
      } | Stage: ${metadata.stage || 'All'} | Risk: ${metadata.risk || 'All'}`,
    ],
    [],
  ];

  const tableHeaders = [
    'Project ID',
    'Project Name',
    'Sector / Type',
    'State',
    'District',
    'Block / Tehsil',
    'Land Area (Ha)',
    'Affected Families',
    'Current Statutory Stage',
    'Status',
    'Start Date',
    'Planned End Date',
    'Actual / Projected End Date',
    'Risk Score (0-100)',
    'Risk Category',
    'Delay Probability (%)',
    'Predicted Delay (Days)',
    'Actual Delay (Days)',
    'Compensation Assessed (₹ Cr)',
    'Compensation Disbursed (₹ Cr)',
    'Compensation DBT %',
    'Physical Possession %',
    'Pending Approvals',
    'Active Legal Writs',
    'R&R Status',
    'Top Delay Driver (SHAP)',
    'Primary Recommended Action',
    'Responsible Authority',
    'SLA (Days)',
    'Stage-Gate Compliance Issues',
  ];

  const dataRows = projects.map((p) => {
    const assessed = p.compensation?.total_compensation_assessed_cr || 0;
    const disbursed = p.compensation?.total_compensation_disbursed_cr || 0;
    const compPct = assessed > 0 ? ((disbursed / assessed) * 100).toFixed(1) + '%' : '0.0%';
    const possessionPct = (p.possession?.possession_percentage || 0) + '%';
    const pendingApps = (p.approvals || []).filter(
      (a) => a.status === 'Pending' || a.status === 'In-Progress'
    ).length;
    const legalCount = (p.legal_disputes || []).filter((l) => l.status === 'Pending').length;
    const topShap = p.prediction?.top_shap_factors?.[0]?.factor || 'N/A';
    const recAction = p.prediction?.recommendations?.[0]?.action || 'Routine progress tracking';
    const recAuth = p.prediction?.recommendations?.[0]?.responsible_authority || 'CALA / Implementing Agency';
    const recSLA = p.prediction?.recommendations?.[0]?.deadline_days || 30;
    const stageIssues = (p.prediction?.stage_gate_issues || []).map((i) => `[${i.type}] ${i.rule}`).join('; ') || 'Compliant';

    return [
      p.project_id,
      p.project_name,
      p.project_type,
      p.state,
      p.district,
      p.block || 'Block-01',
      p.land_area_hectares,
      p.affected_families_count,
      p.current_stage,
      p.project_status,
      p.start_date,
      p.planned_end_date,
      p.actual_end_date || 'Ongoing',
      p.prediction?.risk_score ?? 'N/A',
      p.prediction?.risk_category ?? 'N/A',
      p.prediction?.probability_of_delay ? (p.prediction.probability_of_delay * 100).toFixed(1) + '%' : 'N/A',
      p.prediction?.predicted_delay_days ?? 'N/A',
      p.actual_delay_days ?? (p.project_status === 'Completed' ? 0 : 'N/A'),
      assessed,
      disbursed,
      compPct,
      possessionPct,
      pendingApps,
      legalCount,
      p.rehabilitation?.rr_status || 'Not Started',
      topShap,
      recAction,
      recAuth,
      recSLA,
      stageIssues,
    ];
  });

  const fullSheetData = [...titleRows, tableHeaders, ...dataRows];
  const wsProjects = XLSX.utils.aoa_to_sheet(fullSheetData);

  // Column width hints
  wsProjects['!cols'] = [
    { wch: 14 }, // Project ID
    { wch: 34 }, // Project Name
    { wch: 14 }, // Sector
    { wch: 14 }, // State
    { wch: 14 }, // District
    { wch: 14 }, // Block
    { wch: 14 }, // Land Area
    { wch: 16 }, // Affected Families
    { wch: 18 }, // Current Stage
    { wch: 12 }, // Status
    { wch: 12 }, // Start Date
    { wch: 14 }, // Planned End
    { wch: 14 }, // Actual End
    { wch: 12 }, // Risk Score
    { wch: 14 }, // Risk Category
    { wch: 14 }, // Delay Prob
    { wch: 16 }, // Predicted Delay
    { wch: 14 }, // Actual Delay
    { wch: 18 }, // Compensation Assessed
    { wch: 18 }, // Compensation Disbursed
    { wch: 16 }, // Comp DBT %
    { wch: 16 }, // Possession %
    { wch: 16 }, // Pending Approvals
    { wch: 16 }, // Legal Writs
    { wch: 14 }, // RR Status
    { wch: 28 }, // Top Delay Driver
    { wch: 34 }, // Rec Action
    { wch: 24 }, // Rec Authority
    { wch: 12 }, // SLA
    { wch: 30 }, // Stage Gate Issues
  ];

  XLSX.utils.book_append_sheet(wb, wsProjects, 'Project_Status_Register');

  // Sheet 2: Executive Summary & Risk Analysis
  const highRisk = projects.filter((p) => (p.prediction?.risk_score ?? 0) >= 65);
  const medRisk = projects.filter(
    (p) => (p.prediction?.risk_score ?? 0) >= 35 && (p.prediction?.risk_score ?? 0) < 65
  );
  const lowRisk = projects.filter((p) => (p.prediction?.risk_score ?? 0) < 35);

  const totalAssessed = projects.reduce((acc, p) => acc + (p.compensation?.total_compensation_assessed_cr || 0), 0);
  const totalDisbursed = projects.reduce((acc, p) => acc + (p.compensation?.total_compensation_disbursed_cr || 0), 0);
  const totalLand = projects.reduce((acc, p) => acc + (p.land_area_hectares || 0), 0);
  const totalFamilies = projects.reduce((acc, p) => acc + (p.affected_families_count || 0), 0);

  const summaryData = [
    ['PORTFOLIO RISK & STATUTORY PERFORMANCE EXECUTIVE SUMMARY'],
    ['Generated for:', metadata.officerDesignation || metadata.userRole || 'Competent Authority'],
    ['Date of Assessment:', timestamp],
    [],
    ['KEY PERFORMANCE INDICATORS', 'VALUE', 'UNIT / NOTES'],
    ['Total Monitored Projects', projects.length, 'Packages across active filter scope'],
    ['Active / Ongoing Packages', projects.filter((p) => p.project_status === 'Ongoing').length, 'Under acquisition'],
    ['Completed Packages', projects.filter((p) => p.project_status === 'Completed').length, 'Historical benchmarks'],
    ['High Risk Delinquency Count', highRisk.length, `${((highRisk.length / Math.max(1, projects.length)) * 100).toFixed(1)}% of total`],
    ['Medium Risk Delinquency Count', medRisk.length, `${((medRisk.length / Math.max(1, projects.length)) * 100).toFixed(1)}% of total`],
    ['Low Risk On-Track Count', lowRisk.length, `${((lowRisk.length / Math.max(1, projects.length)) * 100).toFixed(1)}% of total`],
    ['Total Land Under Acquisition', Math.round(totalLand), 'Hectares'],
    ['Total Affected Families', totalFamilies, 'Households recorded'],
    ['Total Assessed Compensation', totalAssessed.toFixed(2), '₹ Crores INR'],
    ['Total Disbursed Compensation', totalDisbursed.toFixed(2), '₹ Crores INR (DBT Transfer)'],
    ['Disbursement Gap (Pending)', (totalAssessed - totalDisbursed).toFixed(2), '₹ Crores INR unreleased'],
    ['Compensation Realization Rate', totalAssessed > 0 ? ((totalDisbursed / totalAssessed) * 100).toFixed(1) + '%' : '0%', 'Direct DBT to bank accounts'],
    [],
    ['HIGH-RISK CRITICAL PACKAGES REQUIRING IMMEDIATE INTERVENTION'],
    ['Project ID', 'Project Name', 'District', 'Sector', 'Stage', 'Risk Score', 'Predicted Delay (Days)', 'Key Bottleneck', 'Recommended Action', 'SLA (Days)'],
    ...highRisk.slice(0, 30).map((p) => [
      p.project_id,
      p.project_name,
      p.district,
      p.project_type,
      p.current_stage,
      p.prediction?.risk_score ?? 0,
      p.prediction?.predicted_delay_days ?? 0,
      p.prediction?.top_shap_factors?.[0]?.factor || 'Disbursement / Approvals lag',
      p.prediction?.recommendations?.[0]?.action || 'Urgent inter-departmental review',
      p.prediction?.recommendations?.[0]?.deadline_days || 15,
    ]),
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  wsSummary['!cols'] = [
    { wch: 32 },
    { wch: 32 },
    { wch: 18 },
    { wch: 16 },
    { wch: 16 },
    { wch: 14 },
    { wch: 20 },
    { wch: 28 },
    { wch: 36 },
    { wch: 12 },
  ];
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive_Risk_Summary');

  // Trigger file download
  const dateTag = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `${fileNamePrefix}_${dateTag}.xlsx`);
}

// ==========================================
// 2. PROJECT LIST PDF EXPORT (.PDF)
// ==========================================
export function exportProjectListToPDF(
  projects: LandProject[],
  metadata: ReportFilterMetadata = {},
  fileNamePrefix: string = 'DoLR_Project_Status_Report'
): void {
  // Create landscape document for tabular breadth
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'pt',
    format: 'a4',
  });

  const docRef = generateDocRef('DoLR-PLIST');
  const timestamp = new Date().toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Primary Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 56, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('GOVERNMENT OF INDIA • MINISTRY OF RURAL DEVELOPMENT', 30, 24);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(203, 213, 225); // slate-300
  doc.text(
    'DEPARTMENT OF LAND RESOURCES (DoLR) | NATIONAL LAND ACQUISITION DELAY SURVEILLANCE SYSTEM',
    30,
    38
  );

  doc.setTextColor(251, 191, 36); // amber-400
  doc.setFont('helvetica', 'bold');
  doc.text('FORMAL STATUS REPORT', pageWidth - 30, 24, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(226, 232, 240);
  doc.text(`Ref: ${docRef}`, pageWidth - 30, 38, { align: 'right' });

  // Sub-header & Report Title
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Statutory Land Acquisition Projects Status & Delay Risk Register', 30, 80);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Audited under RFCTLARR Act, 2013 and ML Early Warning Predictive Engine • Generated: ${timestamp}`,
    30,
    94
  );

  // Metadata Panel / Summary Boxes
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(30, 104, pageWidth - 60, 48, 4, 4, 'FD');

  const highRiskCount = projects.filter((p) => (p.prediction?.risk_score ?? 0) >= 65).length;
  const ongoingCount = projects.filter((p) => p.project_status === 'Ongoing').length;
  const totalAssessed = projects.reduce((acc, p) => acc + (p.compensation?.total_compensation_assessed_cr || 0), 0);
  const totalDisbursed = projects.reduce((acc, p) => acc + (p.compensation?.total_compensation_disbursed_cr || 0), 0);
  const avgDelay = ongoingCount > 0
    ? Math.round(
        projects
          .filter((p) => p.project_status === 'Ongoing')
          .reduce((acc, p) => acc + (p.prediction?.predicted_delay_days || 0), 0) / ongoingCount
      )
    : 0;

  // Box 1: Total Projects
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('TOTAL AUDITED', 45, 120);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(`${projects.length} Packages`, 45, 136);

  // Box 2: High Risk
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(185, 28, 28);
  doc.text('HIGH RISK (RED ALERT)', 170, 120);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(220, 38, 38);
  doc.text(`${highRiskCount} (${((highRiskCount / Math.max(1, projects.length)) * 100).toFixed(0)}%)`, 170, 136);

  // Box 3: Avg Predicted Slippage
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('AVG PREDICTED SLIPPAGE', 315, 120);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(`+${avgDelay} Days`, 315, 136);

  // Box 4: Compensation DBT Progress
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('COMPENSATION DBT', 475, 120);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  const dbtPct = totalAssessed > 0 ? ((totalDisbursed / totalAssessed) * 100).toFixed(0) : '0';
  doc.text(`${dbtPct}% (${formatCr(totalDisbursed)})`, 475, 136);

  // Box 5: Filter Scope
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('APPLIED SCOPE & ROLE', 645, 120);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  const scopeTxt = `${metadata.state || 'All States'} / ${metadata.district || 'All Districts'}`;
  doc.text(scopeTxt.length > 25 ? scopeTxt.substring(0, 24) + '...' : scopeTxt, 645, 134);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Role: ${metadata.userRole || 'Officer'}`, 645, 144);

  // Build Table Data
  const tableHead = [
    [
      'ID',
      'Project Title & Location',
      'Sector',
      'Stage',
      'Land (Ha)',
      'Comp. DBT %',
      'Poss. %',
      'Risk Score',
      'Category',
      'Delay (Days)',
      'Primary Delay Driver / Recommendation',
    ],
  ];

  const tableBody = projects.map((p) => {
    const assessed = p.compensation?.total_compensation_assessed_cr || 0;
    const disbursed = p.compensation?.total_compensation_disbursed_cr || 0;
    const compPct = assessed > 0 ? `${Math.round((disbursed / assessed) * 100)}%` : '0%';
    const possPct = `${p.possession?.possession_percentage || 0}%`;
    const riskScore = p.prediction?.risk_score ?? 0;
    const riskCat = p.prediction?.risk_category ?? 'Low';
    const delayDays = p.project_status === 'Completed'
      ? `${p.actual_delay_days ?? 0} (Act)`
      : `+${p.prediction?.predicted_delay_days ?? 0}`;
    const keyDriver = p.prediction?.top_shap_factors?.[0]?.factor || 'Clearances SLA compliance';
    const recAction = p.prediction?.recommendations?.[0]?.action || 'Routine stage tracking';

    return [
      p.project_id,
      `${p.project_name}\n[${p.district}, ${p.state}]`,
      p.project_type,
      p.current_stage,
      `${p.land_area_hectares} Ha`,
      compPct,
      possPct,
      `${riskScore}/100`,
      riskCat,
      delayDays,
      `${keyDriver} • ${recAction}`,
    ];
  });

  autoTable(doc, {
    head: tableHead,
    body: tableBody,
    startY: 162,
    margin: { left: 30, right: 30, bottom: 40 },
    theme: 'striped',
    styles: {
      fontSize: 7.5,
      cellPadding: 4,
      textColor: [30, 41, 59],
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: [30, 41, 59], // slate-800
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
      halign: 'left',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 50, fontStyle: 'bold' },
      1: { cellWidth: 140 },
      2: { cellWidth: 55 },
      3: { cellWidth: 60 },
      4: { cellWidth: 50, halign: 'right' },
      5: { cellWidth: 55, halign: 'right' },
      6: { cellWidth: 45, halign: 'right' },
      7: { cellWidth: 50, halign: 'center', fontStyle: 'bold' },
      8: { cellWidth: 50, halign: 'center' },
      9: { cellWidth: 60, halign: 'right', fontStyle: 'bold' },
      10: { cellWidth: 165 },
    },
    didParseCell: (data) => {
      // Colorize Risk Category and Score
      if (data.section === 'body') {
        const rawRow = projects[data.row.index];
        const riskScore = rawRow?.prediction?.risk_score ?? 0;
        if (data.column.index === 7 || data.column.index === 8) {
          if (riskScore >= 65) {
            data.cell.styles.textColor = [185, 28, 28]; // red-700
            data.cell.styles.fontStyle = 'bold';
          } else if (riskScore >= 35) {
            data.cell.styles.textColor = [180, 83, 9]; // amber-700
            data.cell.styles.fontStyle = 'bold';
          } else {
            data.cell.styles.textColor = [21, 128, 61]; // green-700
          }
        }
      }
    },
    didDrawPage: (data) => {
      // Footer on each page
      const pageNumber = (doc as any).internal.getNumberOfPages();
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(148, 163, 184); // slate-400

      doc.setDrawColor(226, 232, 240);
      doc.line(30, pageHeight - 26, pageWidth - 30, pageHeight - 26);

      doc.text(
        'Department of Land Resources (DoLR) • Ministry of Rural Development • CONFIDENTIAL & OFFICIAL USE ONLY',
        30,
        pageHeight - 14
      );
      doc.text(
        `Page ${data.pageNumber} of ${pageNumber}`,
        pageWidth - 30,
        pageHeight - 14,
        { align: 'right' }
      );
    },
  });

  const dateTag = new Date().toISOString().slice(0, 10);
  doc.save(`${fileNamePrefix}_${dateTag}.pdf`);
}

// ==========================================
// 3. DASHBOARD EXECUTIVE EXCEL EXPORT (.XLSX)
// ==========================================
export function exportDashboardToExcel(
  projects: LandProject[],
  metadata: ReportFilterMetadata = {},
  fileNamePrefix: string = 'DoLR_Executive_Delay_Surveillance'
): void {
  const wb = XLSX.utils.book_new();
  const timestamp = new Date().toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
  const docRef = generateDocRef('DoLR-EXEC');

  const ongoing = projects.filter((p) => p.project_status === 'Ongoing');
  const completed = projects.filter((p) => p.project_status === 'Completed');
  const highRisk = ongoing.filter((p) => (p.prediction?.risk_score ?? 0) >= 65);
  const medRisk = ongoing.filter(
    (p) => (p.prediction?.risk_score ?? 0) >= 35 && (p.prediction?.risk_score ?? 0) < 65
  );
  const lowRisk = ongoing.filter((p) => (p.prediction?.risk_score ?? 0) < 35);

  const totalAssessed = projects.reduce((acc, p) => acc + (p.compensation?.total_compensation_assessed_cr || 0), 0);
  const totalDisbursed = projects.reduce((acc, p) => acc + (p.compensation?.total_compensation_disbursed_cr || 0), 0);
  const delayedCapitalAtRisk = highRisk.reduce((acc, p) => acc + (p.compensation?.total_compensation_assessed_cr || 0), 0);
  const totalLand = projects.reduce((acc, p) => acc + (p.land_area_hectares || 0), 0);
  const totalFamilies = projects.reduce((acc, p) => acc + (p.affected_families_count || 0), 0);

  const avgDelay = ongoing.length > 0
    ? Math.round(
        ongoing.reduce((acc, p) => acc + (p.prediction?.predicted_delay_days || 0), 0) / ongoing.length
      )
    : 0;

  // Sheet 1: Executive KPI Dashboard
  const summarySheetRows = [
    ['GOVERNMENT OF INDIA - MINISTRY OF RURAL DEVELOPMENT'],
    ['DEPARTMENT OF LAND RESOURCES | NATIONAL LAND ACQUISITION DELAY SURVEILLANCE SYSTEM'],
    ['EXECUTIVE INTELLIGENCE BRIEFING & STATUTORY DELAY AUDIT'],
    [],
    ['Document Reference:', docRef, '', 'Audit Date & Time:', timestamp],
    ['Executive Officer / Role:', metadata.userRole || 'Central Nodal Officer', '', 'Active Filter Scope:', `${metadata.state || 'All States'} / ${metadata.district || 'All Districts'}`],
    [],
    ['SECTION 1: NATIONAL / STATE PORTFOLIO EXECUTIVE METRICS'],
    ['Metric Name', 'Value', 'Unit / Details', 'Statutory Benchmark / Status'],
    ['Total Land Acquisition Packages', projects.length, 'Records', 'RFCTLARR 2013 Monitored'],
    ['Active / Ongoing Acquisitions', ongoing.length, 'Packages in field execution', 'Active legal milestones'],
    ['Completed Benchmark Packages', completed.length, 'Packages closed', 'Historical baselines for ML training'],
    ['High Risk Delinquencies (Score >= 65)', highRisk.length, `${((highRisk.length / Math.max(1, ongoing.length)) * 100).toFixed(1)}% of ongoing`, 'CRITICAL: Requires Immediate Intervention'],
    ['Medium Risk Delinquencies (Score 35-64)', medRisk.length, `${((medRisk.length / Math.max(1, ongoing.length)) * 100).toFixed(1)}% of ongoing`, 'Active monitoring recommended'],
    ['Low Risk On-Track (Score < 35)', lowRisk.length, `${((lowRisk.length / Math.max(1, ongoing.length)) * 100).toFixed(1)}% of ongoing`, 'Healthy trajectory'],
    ['Average Projected Milestone Slippage', `+${avgDelay} Days`, 'Calendar days beyond planned end', 'RFCTLARR Sec 19/25 statutory limits'],
    ['Capital At High Delay Risk', `₹${delayedCapitalAtRisk.toFixed(2)} Cr`, 'Assessed compensation value of high risk packages', 'Public capital locked in delayed projects'],
    ['Total Compensation Assessed', `₹${totalAssessed.toFixed(2)} Cr`, 'Cumulative awards determined', 'Section 23 statutory awards'],
    ['Total Compensation Disbursed (DBT)', `₹${totalDisbursed.toFixed(2)} Cr`, 'Transferred to beneficiary bank accounts', 'Direct Benefit Transfer'],
    ['Compensation Realization Ratio', `${totalAssessed > 0 ? ((totalDisbursed / totalAssessed) * 100).toFixed(1) : 0}%`, 'DBT disbursement vs assessment', 'Target: >80% prior to physical possession'],
    ['Total Land Area Under Acquisition', `${Math.round(totalLand)} Ha`, 'Hectares', 'Linear & Block land parcels'],
    ['Total Project Affected Families (PAFs)', totalFamilies, 'Households', 'Covered under Section 31 R&R schemes'],
    [],
    ['SECTION 2: STATUTORY STAGE BOTTLENECK ANALYSIS'],
    ['Statutory Acquisition Stage', 'Active Packages', 'High Risk Count', 'Average Slippage (Days)', 'Key Bottleneck Factor'],
    ...['Notification', 'Survey', 'Compensation', 'Possession', 'R&R'].map((stg) => {
      const stageProjs = ongoing.filter((p) => p.current_stage === stg);
      const stageHigh = stageProjs.filter((p) => (p.prediction?.risk_score ?? 0) >= 65).length;
      const stageDelay = stageProjs.length > 0
        ? Math.round(stageProjs.reduce((acc, p) => acc + (p.prediction?.predicted_delay_days || 0), 0) / stageProjs.length)
        : 0;
      let bottleneckDesc = 'Inter-departmental approvals';
      if (stg === 'Notification') bottleneckDesc = 'Section 11 gazette notification & Gram Sabha consultation';
      if (stg === 'Survey') bottleneckDesc = 'Joint Measurement Survey (JMS) & boundary demarcation protests';
      if (stg === 'Compensation') bottleneckDesc = 'DBT bank verification, title disputes & award determination';
      if (stg === 'Possession') bottleneckDesc = 'Section 38 prerequisite (unpaid compensation & crops standing)';
      if (stg === 'R&R') bottleneckDesc = 'Section 31 resettlement center readiness & alternative plots';

      return [stg, stageProjs.length, stageHigh, `+${stageDelay} Days`, bottleneckDesc];
    }),
    [],
    ['SECTION 3: SECTOR-WISE RISK CONCENTRATION'],
    ['Sector / Infrastructure Type', 'Total Packages', 'High Risk Packages', 'Avg Risk Score', 'Avg Delay (Days)'],
    ...['Highway', 'Railway', 'Power', 'Irrigation', 'Industrial', 'Urban'].map((sec) => {
      const secProjs = ongoing.filter((p) => p.project_type === sec);
      const secHigh = secProjs.filter((p) => (p.prediction?.risk_score ?? 0) >= 65).length;
      const avgScore = secProjs.length > 0
        ? Math.round(secProjs.reduce((acc, p) => acc + (p.prediction?.risk_score || 0), 0) / secProjs.length)
        : 0;
      const secDelay = secProjs.length > 0
        ? Math.round(secProjs.reduce((acc, p) => acc + (p.prediction?.predicted_delay_days || 0), 0) / secProjs.length)
        : 0;
      return [sec, secProjs.length, secHigh, `${avgScore}/100`, `+${secDelay} Days`];
    }),
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summarySheetRows);
  wsSummary['!cols'] = [
    { wch: 36 },
    { wch: 22 },
    { wch: 26 },
    { wch: 38 },
  ];
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive_Overview');

  // Sheet 2: High-Risk Critical Interventions
  const criticalSheetRows = [
    ['HIGH-RISK CRITICAL PACKAGES INTERVENTION SCHEDULE (Score >= 65)'],
    ['Sorted by Highest Predictive Risk Score • Generated:', timestamp],
    [],
    [
      'Project ID',
      'Project Name',
      'Sector',
      'State',
      'District',
      'Stage',
      'Risk Score',
      'Predicted Delay',
      'Compensation Assessed (₹ Cr)',
      'Compensation Disbursed (₹ Cr)',
      'DBT %',
      'Possession %',
      'Pending Clearances',
      'Legal Writs',
      'Primary Delay Cause (SHAP)',
      'Prescribed Corrective Action',
      'Action Authority',
      'SLA (Days)',
    ],
    ...highRisk
      .sort((a, b) => (b.prediction?.risk_score ?? 0) - (a.prediction?.risk_score ?? 0))
      .map((p) => {
        const assessed = p.compensation?.total_compensation_assessed_cr || 0;
        const disbursed = p.compensation?.total_compensation_disbursed_cr || 0;
        const dbt = assessed > 0 ? ((disbursed / assessed) * 100).toFixed(1) + '%' : '0%';
        return [
          p.project_id,
          p.project_name,
          p.project_type,
          p.state,
          p.district,
          p.current_stage,
          p.prediction?.risk_score ?? 0,
          `+${p.prediction?.predicted_delay_days ?? 0} Days`,
          assessed,
          disbursed,
          dbt,
          `${p.possession?.possession_percentage || 0}%`,
          (p.approvals || []).filter((a) => a.status !== 'Approved').length,
          (p.legal_disputes || []).filter((l) => l.status === 'Pending').length,
          p.prediction?.top_shap_factors?.[0]?.factor || 'Disbursement & Clearance Delays',
          p.prediction?.recommendations?.[0]?.action || 'Establish special fast-track facilitation cell',
          p.prediction?.recommendations?.[0]?.responsible_authority || 'District Collector',
          p.prediction?.recommendations?.[0]?.deadline_days || 15,
        ];
      }),
  ];

  const wsCritical = XLSX.utils.aoa_to_sheet(criticalSheetRows);
  wsCritical['!cols'] = [
    { wch: 14 },
    { wch: 34 },
    { wch: 14 },
    { wch: 14 },
    { wch: 14 },
    { wch: 16 },
    { wch: 12 },
    { wch: 16 },
    { wch: 18 },
    { wch: 18 },
    { wch: 12 },
    { wch: 14 },
    { wch: 18 },
    { wch: 14 },
    { wch: 28 },
    { wch: 36 },
    { wch: 24 },
    { wch: 12 },
  ];
  XLSX.utils.book_append_sheet(wb, wsCritical, 'High_Risk_Action_List');

  // Trigger download
  const dateTag = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `${fileNamePrefix}_${dateTag}.xlsx`);
}

// ==========================================
// 4. DASHBOARD EXECUTIVE PDF EXPORT (.PDF)
// ==========================================
export function exportDashboardToPDF(
  projects: LandProject[],
  metadata: ReportFilterMetadata = {},
  fileNamePrefix: string = 'DoLR_Executive_Status_Report'
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const docRef = generateDocRef('DoLR-EXEC');
  const timestamp = new Date().toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const ongoing = projects.filter((p) => p.project_status === 'Ongoing');
  const highRisk = ongoing.filter((p) => (p.prediction?.risk_score ?? 0) >= 65);
  const medRisk = ongoing.filter(
    (p) => (p.prediction?.risk_score ?? 0) >= 35 && (p.prediction?.risk_score ?? 0) < 65
  );
  const lowRisk = ongoing.filter((p) => (p.prediction?.risk_score ?? 0) < 35);

  const totalAssessed = projects.reduce((acc, p) => acc + (p.compensation?.total_compensation_assessed_cr || 0), 0);
  const totalDisbursed = projects.reduce((acc, p) => acc + (p.compensation?.total_compensation_disbursed_cr || 0), 0);
  const delayedCapitalAtRisk = highRisk.reduce((acc, p) => acc + (p.compensation?.total_compensation_assessed_cr || 0), 0);
  const avgDelay = ongoing.length > 0
    ? Math.round(
        ongoing.reduce((acc, p) => acc + (p.prediction?.predicted_delay_days || 0), 0) / ongoing.length
      )
    : 0;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 60, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('GOVERNMENT OF INDIA • MINISTRY OF RURAL DEVELOPMENT', 30, 24);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(203, 213, 225);
  doc.text(
    'DEPARTMENT OF LAND RESOURCES (DoLR) • NATIONAL LAND ACQUISITION DELAY SURVEILLANCE',
    30,
    38
  );

  doc.setTextColor(251, 191, 36);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('EXECUTIVE STATUS BRIEF', pageWidth - 30, 24, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(226, 232, 240);
  doc.text(`Doc Ref: ${docRef}`, pageWidth - 30, 38, { align: 'right' });

  // Document Title & Executive Memo
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Delay Risk & Statutory Compliance Status Report', 30, 84);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Scope: ${metadata.state || 'All States'} | District: ${metadata.district || 'All'} | Officer Role: ${
      metadata.userRole || 'Central Admin'
    } | Date: ${timestamp}`,
    30,
    98
  );

  // 6 Metric KPI Boxes in a 3x2 Grid
  const cardWidth = (pageWidth - 60 - 20) / 3;
  const cardHeight = 44;

  const kpis = [
    { label: 'MONITORED PROJECTS', val: `${projects.length}`, sub: `${ongoing.length} Ongoing, ${projects.length - ongoing.length} Closed`, color: [15, 23, 42] },
    { label: 'HIGH RISK HOTSPOTS', val: `${highRisk.length}`, sub: `${((highRisk.length / Math.max(1, ongoing.length)) * 100).toFixed(1)}% of active packages`, color: [220, 38, 38] },
    { label: 'AVG PREDICTED SLIPPAGE', val: `+${avgDelay} Days`, sub: 'Beyond RFCTLARR statutory target', color: [180, 83, 9] },
    { label: 'CAPITAL AT RISK', val: formatCr(delayedCapitalAtRisk), sub: 'Assessed value in high risk packages', color: [220, 38, 38] },
    { label: 'COMPENSATION DBT', val: `${totalAssessed > 0 ? ((totalDisbursed / totalAssessed) * 100).toFixed(1) : 0}%`, sub: `${formatCr(totalDisbursed)} of ${formatCr(totalAssessed)}`, color: [22, 101, 52] },
    { label: 'ON-TRACK PACKAGES', val: `${lowRisk.length}`, sub: `${((lowRisk.length / Math.max(1, ongoing.length)) * 100).toFixed(1)}% healthy progression`, color: [22, 101, 52] },
  ];

  kpis.forEach((kpi, idx) => {
    const row = Math.floor(idx / 3);
    const col = idx % 3;
    const x = 30 + col * (cardWidth + 10);
    const y = 112 + row * (cardHeight + 8);

    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, y, cardWidth, cardHeight, 4, 4, 'FD');

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(kpi.label, x + 8, y + 12);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(kpi.color[0], kpi.color[1], kpi.color[2]);
    doc.text(kpi.val, x + 8, y + 27);

    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(kpi.sub, x + 8, y + 38);
  });

  // Section: Stage-Gate Bottleneck Performance Table
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10.5);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Statutory Stage-Gate Bottleneck Analysis (RFCTLARR Act)', 30, 230);

  const stageHead = [['Acquisition Stage', 'Active Packages', 'High Risk', 'Avg Delay', 'Statutory Trigger & Vulnerability']];
  const stageData = ['Notification', 'Survey', 'Compensation', 'Possession', 'R&R'].map((stg) => {
    const stageProjs = ongoing.filter((p) => p.current_stage === stg);
    const stageHigh = stageProjs.filter((p) => (p.prediction?.risk_score ?? 0) >= 65).length;
    const stageDelay = stageProjs.length > 0
      ? Math.round(stageProjs.reduce((acc, p) => acc + (p.prediction?.predicted_delay_days || 0), 0) / stageProjs.length)
      : 0;
    let desc = 'Clearances & gazette notification timeline';
    if (stg === 'Notification') desc = 'Section 11 Preliminary notification lapses if Section 19 declaration not issued in 12 mos';
    if (stg === 'Survey') desc = 'JMS land boundary disputes, field parcel mapping & ownership verification delays';
    if (stg === 'Compensation') desc = 'Section 23 award determination & DBT bank account validation backlogs';
    if (stg === 'Possession') desc = 'Section 38 prerequisite (no possession before 80% compensation disbursed)';
    if (stg === 'R&R') desc = 'Section 31 Rehabilitation & Resettlement infrastructure handovers';

    return [stg, `${stageProjs.length}`, `${stageHigh}`, `+${stageDelay} Days`, desc];
  });

  autoTable(doc, {
    head: stageHead,
    body: stageData,
    startY: 238,
    margin: { left: 30, right: 30 },
    theme: 'grid',
    styles: { fontSize: 7.5, cellPadding: 3.5, textColor: [30, 41, 59] },
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 80, fontStyle: 'bold' },
      1: { cellWidth: 60, halign: 'center' },
      2: { cellWidth: 50, halign: 'center', textColor: [185, 28, 28], fontStyle: 'bold' },
      3: { cellWidth: 65, halign: 'right', fontStyle: 'bold' },
      4: { cellWidth: 280 },
    },
  });

  const finalY1 = (doc as any).lastAutoTable.finalY + 18;

  // Section: High Risk Packages Table
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10.5);
  doc.setFont('helvetica', 'bold');
  doc.text('2. Critical High-Risk Packages Requiring Immediate Administrative Intervention', 30, finalY1);

  const highRiskHead = [['Project ID & Name', 'District', 'Sector', 'Stage', 'Score', 'Predicted Delay', 'Top Bottleneck Driver', 'Prescribed SLA']];
  const highRiskRows = highRisk
    .sort((a, b) => (b.prediction?.risk_score ?? 0) - (a.prediction?.risk_score ?? 0))
    .slice(0, 10)
    .map((p) => [
      `${p.project_id}\n${p.project_name.substring(0, 24)}...`,
      p.district,
      p.project_type,
      p.current_stage,
      `${p.prediction?.risk_score ?? 0}/100`,
      `+${p.prediction?.predicted_delay_days ?? 0}d`,
      p.prediction?.top_shap_factors?.[0]?.factor || 'Disbursement delay',
      `${p.prediction?.recommendations?.[0]?.deadline_days || 15} Days`,
    ]);

  autoTable(doc, {
    head: highRiskHead,
    body: highRiskRows,
    startY: finalY1 + 8,
    margin: { left: 30, right: 30, bottom: 50 },
    theme: 'striped',
    styles: { fontSize: 7, cellPadding: 3, textColor: [30, 41, 59] },
    headStyles: { fillColor: [153, 27, 27], textColor: [255, 255, 255], fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 120, fontStyle: 'bold' },
      1: { cellWidth: 55 },
      2: { cellWidth: 50 },
      3: { cellWidth: 55 },
      4: { cellWidth: 45, halign: 'center', textColor: [185, 28, 28], fontStyle: 'bold' },
      5: { cellWidth: 55, halign: 'right', fontStyle: 'bold' },
      6: { cellWidth: 105 },
      7: { cellWidth: 50, halign: 'center', fontStyle: 'bold' },
    },
    didDrawPage: (data) => {
      const pageNumber = (doc as any).internal.getNumberOfPages();
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(148, 163, 184);

      doc.setDrawColor(226, 232, 240);
      doc.line(30, pageHeight - 26, pageWidth - 30, pageHeight - 26);

      doc.text(
        'Department of Land Resources (DoLR) • Ministry of Rural Development • CONFIDENTIAL & OFFICIAL USE ONLY',
        30,
        pageHeight - 14
      );
      doc.text(
        `Page ${data.pageNumber} of ${pageNumber}`,
        pageWidth - 30,
        pageHeight - 14,
        { align: 'right' }
      );
    },
  });

  const finalY2 = (doc as any).lastAutoTable.finalY + 16;
  if (finalY2 < pageHeight - 70) {
    // Official Authentication Sign-off block
    doc.setDrawColor(203, 213, 225);
    doc.line(30, finalY2, pageWidth - 30, finalY2);

    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('OFFICIAL VERIFICATION & TRANSMISSION CERTIFICATE', 30, finalY2 + 14);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(
      'This document is generated by the AI/ML Delay Surveillance Engine under DoLR oversight. Data represents real-time state land acquisition telemetry.',
      30,
      finalY2 + 25
    );

    // Signatures
    doc.text('Prepared By: Land Acquisition Officer / System', 30, finalY2 + 45);
    doc.text('Endorsed By: District Collector / Competent Authority (CALA)', 300, finalY2 + 45);
    doc.text('Date & Digital Stamp: Verified', pageWidth - 160, finalY2 + 45);
  }

  const dateTag = new Date().toISOString().slice(0, 10);
  doc.save(`${fileNamePrefix}_${dateTag}.pdf`);
}
